default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: <%= ENV["DATABASE_PASSWORD"] %>
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: icert_development
  host: icert.airfont.com

test:
  <<: *default
  database: icert_test

production:
  <<: *default
  database: icert_production
  username: root
  # password: <%= ENV['ICERT_DATABASE_PASSWORD'] %>
