default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: <%= ENV["DATABASE_PASSWORD"] %>
  # socket: /tmp/mysql.sock
  host: 140.137.207.47
  database: icert_production
  # password: icert1234
  # host: localhost
  # host: icert.airfont.com
  socket: /var/run/mysqld/mysqld.sock
  password: icert1234

  # socket: /tmp/mysql.sock
  # host: localhost
  # password: <%= ENV['DATABASE_PASSWORD'] %>

development:
  <<: *default
  # database: icert_development
  # socket: /var/run/mysqld/mysqld.sock
  # database: icert_production
  # socket: /var/run/mysqld/mysqld.sock


test:
  <<: *default
  # socket: /tmp/mysql.sock
  # host: localhost
  # password: <%= ENV['DATABASE_PASSWORD'] %>
  database: icert_test

production:
  <<: *default
  # database: icert_production
  socket: /var/run/mysqld/mysqld.sock
  password: icert1234
  # password: <%= ENV['ICERT_DATABASE_PASSWORD'] %>
